### ISSUE TITLE
It is not possible to create a Schedule by submitting the Form

### ISSUE THREAD

**Issue by Gemineye** [J-Mose/CommandSchedulerBundle#107]
This Error occurs: "Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() before Form::isVali"

We Use Symfony 4.1.

**Comment by chrisjohnson00** [comment]
bundle version?

**Comment by Gemineye** [comment]
2.*

You have to use  
if ($scheduledCommandForm->isSubmitted() && $scheduledCommandForm->isValid()) 

instead of
if ($scheduledCommandForm->isValid())

**Comment by Gemineye** [comment]
Just try to add a schedule. If you press the save button nothing happens and the form keeps visible without any user feedback.

**Comment by fyrye** [comment]
The use of calling `isValid` before `isSubmitted` was changed in 3.2 and throws an Exception in 4.0+ 

- Symfony Documentation reference: [Handling Form Submissions](https://symfony.com/doc/current/forms.html#handling-form-submissions)
- Symfony 3.2 Depreciation reference: https://github.com/symfony/symfony/pull/17644
