### ISSUE TITLE
[2.0.0] Configuration - Invalid default value for monitor_mail_subject

### ISSUE THREAD

**Issue by fyrye** [J-Mose/CommandSchedulerBundle#108]
The default value for the `monitor_mail_subject` configuration uses 
`->scalarNode('monitor_mail_subject')->defaultValue('cronjob monitoring %s, %s')->end()`

When using literal `%` within the Config it must be escaped by using `%%`.

See note in the Symfony Documentation: [Parameters in Configuration Files](https://symfony.com/doc/current/service_container/parameters.html#parameters-in-configuration-files)
> If you use a string that starts with @ or has % anywhere in it, you need to escape it by adding another @ or %:

As a result the current release of 2.0.0 will fail to `warmup` with an error trying to find parameter "`s, `".

For others looking to circumvent the issue until fixed, you can override the config value in your parameters.

```yml
jmose_command_scheduler:
    monitor_mail_subject: 'cronjob monitoring %%s, %%s'
```

**Comment by alexsegura** [comment]
+1
