### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by Beagon** [J-Mose/CommandSchedulerBundle#115]
Hi @J-Mose,

I see the last update/merge has been done on April 29th while a lot of people have opened Pull Requests and Issues. So my question is: Is this package still being maintained and if not, would you mind if someone with more time could take over?

Sincerely,

Robin

**Comment by spolischook** [comment]
@tis-dm-webfactory @tikoflano @Pierstoval anyone?

**Comment by Pierstoval** [comment]
I don't know, I'm not the maintainer 😄 

If you think the bundle can be improved, I suggest you propose issues for RFCs or directly submit a PR and wait for @J-Mose to answer 😉

**Comment by chrisjohnson00** [comment]
Last commit was 16 days ago. It is maintained, just moves slowly at times. I've watched and seen consistent (just not often) action on the project over the last few years.

**Comment by J-Mose** [comment]
Hi,

The package is still maintained, but as @chrisjohnson00  pointed it out, it moves slowly :)
I was away from Symfony dev for few months and I will try to catch up with pull requests.

I will focus on comptability issues and bug fixing.
