### ISSUE TITLE
Compatibility with symfony 4.2

### ISSUE THREAD

**Issue by chiqui3d** [J-Mose/CommandSchedulerBundle#116]
I just installed and have many deprecates

**Comment by gubler** [comment]
Symfony Profiler is reporting:

- Extending `Controller` instead of `AbstractController` in `BaseController`
- Referencing controllers with `JMoseCommandSchedulerBundle:{controller}:{action}` (suggested to use `JMose\CommandSchedulerBundle\Controller\{controller}::{action}`
    - Example: `JMoseCommandSchedulerBundle:List:index` -> `JMose\CommandSchedulerBundle\Controller\ListController::indexAction`

**Comment by J-Mose** [comment]
Fixed in #118

**Comment by J-Mose** [comment]
@chiqui3d , thank your for pointing this. It has been fixed.
