### ISSUE TITLE
[question] Is there a way to execute `scheduler:execute` command in long-running mode?

### ISSUE THREAD

**Issue by phansys** [J-Mose/CommandSchedulerBundle#119]
If that command must be executed manually, I think I'm missing something about how it works.
Thank you.

**Comment by J-Mose** [comment]
Indeed, `sheduler:execute` need to be executed (probably in your cronjob file)

The bundle does not replace the OS scheduler, but give a single entry point to your commands (and handle queue / priority to avoid multiple command to run simultanously)
