### ISSUE TITLE
Define jmose_command_scheduler.log_path in bundle's config

### ISSUE THREAD

**Issue by diimpp** [J-Mose/CommandSchedulerBundle#15]
It's a more usual way to expose configuration to users. (JMose/CommandSchedulerBundle/DependencyInjection/Configuration.php)
Might as well add option to log only errors and don't log at all.

**Comment by J-Mose** [comment]
Bundle's configuration has been commited few hours ago (only on dev-master for now)

And you are right, I will implement a `--quiet` option on `scheduler:execute` to avoid useless logs in cron output file.

**Comment by J-Mose** [comment]
`no-output` option added in 1.0.4
