### ISSUE TITLE
Entity defaults absence with required db properties casing error

### ISSUE THREAD

**Issue by diimpp** [J-Mose/CommandSchedulerBundle#17]
Hi,

I'm using entity from personal controller and getting sql constraint violation error, because optional entity properties have no defaults and are required by db.

I think ScheduledCommand init() method violates some OOP principles, as user of class shouldn't know about internals.
Therefore I would suggest to initialize defaults from __construct()
```
     /**
      * Constructor
      */
     public function __construct()
     {
         $this->setLastExecution(new \DateTime);
         $this->setExecuteImmediately(false);
         $this->setDisabled(false);
         $this->setLocked(false);
     }
```
or remove db constraints.

I would be glad to make PR, but which way would you prefer?

Regards.

**Comment by J-Mose** [comment]
Hi, 

Inded, you are right about placing this in `__construct`.
I will probably work on the bundle this week end to apply some optimizations, but don't hesitate to make PR :)
