### ISSUE TITLE
Symfony 5.3 with the LiipTestFixturesBundle

### ISSUE THREAD

**Issue by Chris53897** [J-Mose/CommandSchedulerBundle#198]
There is a conflict in dev with testing with Symfony 5.3 with the LiipTestFixturesBundle.
https://github.com/liip/LiipTestFixturesBundle/issues/112

It is not a problem of the CommandSchedulerBundle. 
But the fix is not yet integrated in the 1.x Branch from LiipTestFixturesBundle.

**Comment by alexislefebvre** [comment]
This issue was fixed in https://github.com/liip/LiipTestFixturesBundle/pull/139
