### ISSUE TITLE
Logging to syslog

### ISSUE THREAD

**Issue by austerus** [J-Mose/CommandSchedulerBundle#21]
Hello,

Is there a way to enable logging via Monolog in this bundle rather than to file? In our current system we use Monolog to log to syslog, it would be great if this bundle would support logging via Monolog too (or have an independent way of writing in syslog).

Thanks!

**Comment by J-Mose** [comment]
Hi, 

Actually, there is no way to log via Monolog or other, but it's a good idea.
I'll probably add this feature in a future version (but i wont work on this bundle for the fews next weeks)

**Comment by Eatmeatleet** [comment]
I also ran into this trouble. From command I call a service, inside a service I have monolog logger but it doesn't write to chosen files

**Comment by J-Mose** [comment]
I think we can handle this with the monolog console logger now.
