### ISSUE TITLE
Warning (fopen()) on scheduler:execute when using log_path : false

### ISSUE THREAD

**Issue by millenc** [J-Mose/CommandSchedulerBundle#27]
Hi,

I'm currently using the `v1.2.1` version of this bundle (commit `84e86f9`) and I've stumbled upon a bug when using the `log_path: false` configuration option in `config.yml`. I want to disable all logging so I'm using this option as per the documentation. The problem is that when this option is set and I run the `scheduler:execute` command I get the following warning:

```
  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: fopen(): Filename cannot be empty
```

The problem lies on [this line](https://github.com/J-Mose/CommandSchedulerBundle/blob/v1.2.1/Command/ExecuteCommand.php#L170):

```php
        // Use a StreamOutput or NullOutput to redirect write() and writeln() in a log file
        if (false === $this->logPath && "" != $scheduledCommand->getLogFile()) {
            $logOutput = new NullOutput();
        }else{
            $logOutput = new StreamOutput(fopen(
                $this->logPath . $scheduledCommand->getLogFile(), 'a', false
            ),$this->commandsVerbosity );
        }
```
The first conditional is wrong, because when `$this->logPath` is false and `$scheduledCommand->getLogFile()` is empty (I haven't configured any log file name when creating my scheduled command) it creates an StreamOutput pointing to an empty file (hence the fopen() error) instead of using the NullOutput. I think this should be changed to:

```php
        // Use a StreamOutput or NullOutput to redirect write() and writeln() in a log file
        if (false !== $this->logPath && "" != $scheduledCommand->getLogFile()) {
            $logOutput = new StreamOutput(fopen(
                $this->logPath . $scheduledCommand->getLogFile(), 'a', false
            ),$this->commandsVerbosity );
        }else{
            $logOutput = new NullOutput();
        }
```
This will create an StreamOutput only if there is a proper (non false) logPath defined and the Log file name is not empty (if it's empty we can assume there is no interest in logging the output so we can disable logging for individual commands). If logPath is false or the log file name is empty we'll just use NullOutput.

Please let me know what you think (I can create a pull request with the proposed fix if you want).

Cheers,
Mikel.

**Comment by J-Mose** [comment]
Thanks, fix in 1.2.2
