### ISSUE TITLE
cron not running 

### ISSUE THREAD

**Issue by prabhukhanna** [J-Mose/CommandSchedulerBundle#30]
I have installed CommandSchedularBundle via composer. I have got the all the screens. I have created two schedulers. One for every 10 mins and the other for every 5 mins. The sehedulers runs only when I run this command `php bin/console scheduler:execute` 

When I go to monitor page it always gives empty array **[ ]** which means everything ok.

Am I missing any configurations ? Or should I want to enable any PHP extensions ?

**Comment by J-Mose** [comment]
Hi, 

The bundle's goal is to have a single entry point to all Symfony task (and then, manage priority and more).

But you still have to execute regularly the `scheduler:execute` command. One by minute or more, according to your needs. 

Best regards
