### ISSUE TITLE
Scheduler logs rotation

### ISSUE THREAD

**Issue by nicogies** [J-Mose/CommandSchedulerBundle#33]
Hello there,

Regarding the logs created by the scheduler, is there a mechanism to enable logs rotation ?
ping @anacicconi

Thanks
Nicolas

**Comment by chrisjohnson00** [comment]
IMO the app shouldn't do this.  There are many tools around that handle this... for example https://www.digitalocean.com/community/tutorials/how-to-manage-log-files-with-logrotate-on-ubuntu-12-10
