### ISSUE TITLE
incompatible with FOSElasticaBundle?

### ISSUE THREAD

**Issue by Badlapje** [J-Mose/CommandSchedulerBundle#36]
I just tried to install this bundle, but got this message from Composer:

> C:\mysymfonyproject-folder\ composer require jmose/command-sch
> eduler-bundle
> Failed loading C:\php\ext\php_xdebug-2.4.0-5.6-vc11-x86_64.dll
> Using version ^1.2 for jmose/command-scheduler-bundle
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>  Problem 1
>     - Conclusion: remove friendsofsymfony/elastica-bundle 4.0.x-dev
>     - Conclusion: don't install friendsofsymfony/elastica-bundle 4.0.x-dev
>     - don't install friendsofsymfony/elastica-bundle 4.0.x-dev|install friendsofsymfony/elastica-bundle dev-master
>     - Conclusion: remove ruflin/elastica 3.1.1
>     - Installation request for friendsofsymfony/elastica-bundle (locked at 4.0.x-dev, required as dev-master) -> satisfi
> able by friendsofsymfony/elastica-bundle[4.0.x-dev].
>     - Conclusion: don't install ruflin/elastica 3.1.1
>     - friendsofsymfony/elastica-bundle dev-master requires ruflin/elastica ~2.1 -> satisfiable by ruflin/elastica[2.1.0,
>  2.2.0, 2.2.1, 2.3.0, 2.3.1].
>     - Can only install one of: ruflin/elastica[2.1.0, 3.1.1].
>     - Can only install one of: ruflin/elastica[2.2.0, 3.1.1].
>     - Can only install one of: ruflin/elastica[2.2.1, 3.1.1].
>     - Can only install one of: ruflin/elastica[2.3.0, 3.1.1].
>     - Can only install one of: ruflin/elastica[2.3.1, 3.1.1].
>     - Installation request for ruflin/elastica (locked at 3.1.1) -> satisfiable by ruflin/elastica[3.1.1].
> 
> Installation failed, reverting ./composer.json to its original content.

I don't know what the issue is with the FOSElasticaBundle, i don't see why it should clash, given Doctrine is used as a primary datastore?

**Comment by chrisjohnson00** [comment]
@Badlapje  could you please post your `composer.json` file?  It may also be helpful to run `composer require jmose/command-scheduler-bundle -vvv` as this should give more information on what is conflicting.

**Comment by Badlapje** [comment]
Hi Chris,

i've since moved on from the project where i needed this.  Thx for replying though!

**Comment by chrisjohnson00** [comment]
Thanks @Badlapje  - good luck to you!
