### ISSUE TITLE
Command not execution automatically

### ISSUE THREAD

**Issue by hermandinho** [J-Mose/CommandSchedulerBundle#40]
Hello all, i don't know what i am doing wrong, but my commands do not execute automatically after the given time i gave while creating the task. it only executes when a launch `php bin/console scheduler:execute --env=env -vvv` in console. 

Regards.

**Comment by thibaudgirard** [comment]
Hi !
To execute the cron job you should add to your system crontab a job which will execute the `php bin/console scheduler:execute`  every minutes. Then create your own jobs through the web interface and all your jobs will be executed in the right moment.
See the example :
`*	*	*	*	*	/path/to/php /path/to/symfony/bin/console scheduler:execute`
This command will execute all your the cron jobs you saved. It's said in the [doc](https://github.com/J-Mose/CommandSchedulerBundle/blob/master/Resources/doc/index.md#usage) : 

> After that, you have to set (every few minutes, it depends of your needs) the following command in your system

Regards ;)

**Comment by hermandinho** [comment]
Thanks @thibaudgirard . Worked fine :)

**Comment by adonix** [comment]
Somehow I was thinking that running `php bin/console scheduler:execute --env=env -vvv` would automatically take care of all the crontab itself, but adding a system crontab to the scheduler works. Thanks!

**Comment by Gargantuas** [comment]
Hi,

Iam on Ubuntu 16.04, i write in the file "/etc/crontab" this command "* * * * * php /my/path/symfony/app/console scheduler:execute" (iam on symfony 2.5) and... nothing happen.

thanks for help.

**Comment by thibaudgirard** [comment]
Hi @Gargantuas,

Try to update your command with your full path of the php executable like that (for exemple) :

`* * * * * /opt/plesk/php/5.6/bin/php /my/path/symfony/app/console scheduler:execute`

;)

**Comment by xorgxx** [comment]
hi i'm on simpleHosting gandi and i try to add task on anacrontab like this : 
```
@daily 0 cron.daily php -f /srv/data/web/vhosts/www.pets.me/htdocs/bin/console.php scheduler:execute
1@hourly 0 cron.daily php-cli -f /srv/data/web/vhosts/www.pets.me/htdocs/bin/console.php scheduler:execut

```
the command by SSH (console mode) to scheduler:execute work perfect! but not on anacrontab.

can you help?
