### ISSUE TITLE
Fill for missed jobs

### ISSUE THREAD

**Issue by javitoxhz** [J-Mose/CommandSchedulerBundle#42]
For example, if a command suppose to run each minute, but the scheduler:execute command was not executed by 5 minutes, when resuming the work it should schedule 5 jobs instead of just one, this way it will "fill the gap" of jobs that were supposed to be done.

Sorry for my english,
thank you !

**Comment by J-Mose** [comment]
I'am afraid that will bring some trouble and unexpected behaviour in most case. 😕
Setting the `scheduler:execute` frequency according your needs seems better to me
