### ISSUE TITLE
cron not running

### ISSUE THREAD

**Issue by marcusfritze** [J-Mose/CommandSchedulerBundle#46]
when I run `php app/console scheduler:execute --dump`

it says
`Start : Dump all scheduled command
Immediately execution asked for : app:mycommand`

but no log-file is generated and I think my command is not executed (I don't the any results - it should generate a file)

But when I type my command
`php app/console app:mycommand`
it works without any problems. 

I set the log_path and even created the logFile.log which I also use as name for the output log (myFile.log).

Any help for debugging appreciated. Thanks.

**Comment by FilippoGiove** [comment]
I have the same issue.
Any suggestions?

Thanks.

**Comment by eved42** [comment]
I haven't tested this bundle yet but maybe you have to specify the environment in your command ?
`php bin/console scheduler:execute --dump --env=prod`

**Comment by J-Mose** [comment]
Hi, 

The `--dump` option is for debug purpose, (it write command's state without execution), so just remove this one.

It's a documentation mistake. Sorry about that !
