### ISSUE TITLE
including custom commands 

### ISSUE THREAD

**Issue by katawura** [J-Mose/CommandSchedulerBundle#49]
Is there a way to include commands that you create by yourself in the detail.command dropdown? Currently got a command that l have personally created and wanted to add it into the cron list but it doesn't seem to appear in the dropdown.

**Comment by J-Mose** [comment]
Hi, 

All Symfony commands should appears in the dropdown (even those you created).

Here is the excluded namespaces (but if needed, you can override this list in your `config.yml`)
- '_global'
- 'scheduler',
- 'server',
- 'container',
- 'config',
- 'generate',
- 'init',
- 'router'

The dropdown is built with the native `app/console list`, so your command have to be recognized by Symfony.

However, others native PHP script are not supported by the bundle.
