### ISSUE TITLE
Why forcing the doctrine naming strategy ?

### ISSUE THREAD

**Issue by Glideh** [J-Mose/CommandSchedulerBundle#50]
Is there a reason why we are specifying the column names in the mapping ?

I'm personally using Symfony's default naming strategy for Doctrine (with is lowercase underscore), and the bundle creates this only one full uppercased table.

Since we can't override the mapping, shouldn't we remove the column names so Doctrine can fallback on the configured strategy ?

Great bundle by the way !

**Comment by Gemorroj** [comment]
@J-Mose can you merge this pr?

**Comment by Glideh** [comment]
@J-Mose was waiting the next major release since it is a breaking change causing a full data loss.
Maybe we could provide a migration.

**Comment by chrisjohnson00** [comment]
yes to migration strategy.  seems like the migration would require
 

1. determine the source of the data, columns etc (easy)
2. determine the X number of destinations, based on naming strategy (should be easy)
3. generate X migration scripts for MySQL, other databases too??
 
Alternatively, provide steps for users on how to create a migration script using the [doctrine migration bundle](https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html), which will handle migrations for all supported doctrine backends.

**Comment by J-Mose** [comment]
Merge in 2.0
