### ISSUE TITLE
Cannot schedule commands that use Symfony arguments instead of Options

### ISSUE THREAD

**Issue by bflick** [J-Mose/CommandSchedulerBundle#55]
Commands that have been written to accept arguments cannot be run by scheduler. Every "argument" as refered to by the "Arguments" field in the command building form must actually be a Symfony "InputOption". I would like to be able to schedule commands that have required arguments so they do not need to be optional arguments when in fact they are required.

**Comment by bflick** [comment]
Also, there is an issue with symfony command options that are supplied as arrays. The convention for this is to pass the same option multiple times with different values. 

e.g. php my-app:mycmd --opt1=something --opt1=somethingelse --opt2=somethingentirelydifferent

I can't run commands like that with the scheduler provided with this package.

**Comment by tikoflano** [comment]
@bflick Regarding your first question, you CAN use arguments, but they are not defined the same way you would do when calling the same command from a console. 

Assuming you have an argument called **target**:

- In a console you would call `my:command target1` and you would have `target1` as the argument value.
- Using the scheduler you need to call `my:command target=target ` and you would have `target1` as the argument value.

Right now you can't use values containing white spaces neither in arguments nor options, but I sent a pull request (#58) to improve.

If this solves your problem I think it would be better to close this issue and open a new one with your second problem as they are not related.

**Comment by chrisjohnson00** [comment]
i believe this issue can be closed as the fix was introduced in 1.2.4
