### ISSUE TITLE
No block "form_start" found while rendering the form

### ISSUE THREAD

**Issue by marcosangiovanni** [J-Mose/CommandSchedulerBundle#61]
After install i always get this error

**Comment by J-Mose** [comment]
witch version of Symfony do you use ?

**Comment by marcosangiovanni** [comment]
2.8 Are there other infos i can give you to help solve the problem?

**Comment by J-Mose** [comment]
When do you have this error exactly ? when creating a new command ? the list view is working ?
Please paste here the full error message.

**Comment by marcosangiovanni** [comment]
Hi,

yes the list view is working (but empty).
I get this error when i try to create a new task and when i try to edit an existing task. 
(To insert the task I insert directly the data in DB)

COMPLETE ERROR :
An exception has been thrown during the rendering of a template ("No block "form_start" found while rendering the form.").
500 Internal Server Error - Twig_Error_Runtime
1 linked Exception: LogicException »

![selection_055](https://cloud.githubusercontent.com/assets/24589227/23408867/de1bf9ca-fdc9-11e6-862c-ba61f885bd01.png)

**Comment by chrisjohnson00** [comment]
@marcosangiovanni can you also mention what version of the bundle you are using?  You should find this information in your composer.lock file or by copy/pasting the output of `composer show`
