### ISSUE TITLE
Command not execution automatically

### ISSUE THREAD

**Issue by Gargantuas** [J-Mose/CommandSchedulerBundle#75]
Hi,

Iam on Ubuntu 16.04, i write in the file "/etc/crontab" this command "* * * * * php /my/path/symfony/app/console scheduler:execute" (iam on symfony 2.5) and... nothing happen.
I am on version 1.1.x for this bundle.
And anything other command in my crontab works.

thanks for help.

**Comment by chrisjohnson00** [comment]
what happens when you run `php /my/path/symfony/app/console scheduler:execute` manually?

**Comment by Gargantuas** [comment]
if i do it manually it works.

**Comment by PhilETaylor** [comment]
I get this in the log:

```
[2017-09-03 18:24:01] console.ERROR: Error thrown while running command "scheduler:execute --env=prod --no-output". Message: "The StreamOutput class needs a stream as its first argument." {"error":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The StreamOutput class needs a stream as its first argument. at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Output/StreamOutput.php:48)","command":"scheduler:execute --env=prod --no-output","message":"The StreamOutput class needs a stream as its first argument."} []
```

**Comment by PhilETaylor** [comment]
ok found my problem. I had set a full path to the log file, which meant that when you added the prefix to the log file path it errored as it could not open the log file. 

So my fix was to set the log_path correctly in the config.yml and then not to use a path, just give the command the name of a log file

The above error needs fixing though, line 198 of ExecuteCommand.php - needs to check if the fopen() returns false (cause it cant open the file with invalid path) and then throw an exception.

**Comment by chrisjohnson00** [comment]
@Gargantuas sorry for the delay on this... were you able to get things figured out?  It seems like an issue with the cron setup since you can execute it manually.

**Comment by Martin89PL** [comment]
Hello,
I have the same issue. Command works only when I doing: php bin/console scheduler:execute
But not works from this bundle. 
![issue](https://user-images.githubusercontent.com/19622673/32810393-ffd0076c-c99a-11e7-87c7-e56cfccf28cf.png)

**Comment by chrisjohnson00** [comment]
@Martin89PL would you please post your crontab entry?

**Comment by Martin89PL** [comment]
Really sorry. I forget to add execute to crontab job on mine machine.

**Comment by ahromets** [comment]
So to make it workable I need manually write the line to the system crontab? In this way cron is works, but why I need this extension in this case?
In another way if I only create command and scheduled command by documentation and run my command with `php console scheduler:execute` it run just once.
```[2017-12-12 17:41:00] app.INFO: The cron is works! [] ```

**Comment by chrisjohnson00** [comment]
I used this package at my past company, where the development team had no access/responsibility to manage crontab. This package gave us the ability to create, monitor, etc "cron jobs" without direct access to the box.
The core ability of this package is to allow you to easily schedule, exec & monitor commands in the Symfony project without making system level changes.
You are right, you don't need this, but it gives things to you that crontab doesn't do or doesn't do as nicely (manual execution & programatic monitoring)

**Comment by ahromets** [comment]
Upd.
I did it wrong!
For make it workable, you should add to crontab only one command:
`bin/console scheduler:execute`
And others command you should add through `http://{your-app-root}/command-scheduler/detail/new` and everything will work!
