### ISSUE TITLE
adding task on anacrontab

### ISSUE THREAD

**Issue by xorgxx** [J-Mose/CommandSchedulerBundle#76]
hi, i trying to use your bundle for one week.

all are working perfect in SSH mode, but when i add task in anacronatb then das not work !!

i get this error : 
```                                            
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "scheduler:execute
" is not defined.                    
  Did you mean one of these?                                      
      scheduler:execute                                           
      scheduler:monitor   
 ```
this the command linge i deed add in anacrontab file : 

```
@hourly 0 cron.daily-1 php -f /srv/data/web/vhosts/www.pets.me/htdocs/bin/console scheduler:execute
```
i dont know want to do, i m bloque.

thank

**Comment by chrisjohnson00** [comment]
can you check your anacrontab (which i've not used), to see if there's a line break character?  The ```Command "scheduler:execute
" is not defined.``` including a line break makes me wonder if that's the case.

**Comment by xorgxx** [comment]
hi thank.

so i dont know what i can show to exatly so here is the full log as it show to me : 
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "scheduler:execute
" is not defined.                    
  Did you mean one of these?                                      
      scheduler:execute                                           
      scheduler:monitor                                           
                                                                  


                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "scheduler:execute
" is not defined.                    
  Did you mean one of these?                                      
      scheduler:execute                                           
      scheduler:monitor                                           
  ```
and here is the anacrontab file : 

![2017-09-16_15-23-30](https://user-images.githubusercontent.com/7679725/30512585-46797e04-9af3-11e7-948e-d8d75191eb56.jpg)

hope it can help. but i try last day to put one command ligne strait to "php file" it work.

**Comment by xorgxx** [comment]
so have change crlf to LF and you where true i think that it work now better.

**Comment by chrisjohnson00** [comment]
yeah, or run `dos2unix` on the file on the unix server before loading it into anacron/
