### ISSUE TITLE
Override/estends template.

### ISSUE THREAD

**Issue by xorgxx** [J-Mose/CommandSchedulerBundle#79]
Hi im want to know if you plan to give possibility to override template so it can be possible to extends in twig, to have the possibility to "include" the main style.

Thank

**Comment by chrisjohnson00** [comment]
see pr #68, i've included templating in the emails, you should be able to override the regular/web twig templates using the same methods described for the emails.

**Comment by xorgxx** [comment]
OK great !! thank.
