### ISSUE TITLE
Error in log_path

### ISSUE THREAD

**Issue by roberto910907** [J-Mose/CommandSchedulerBundle#80]
With the default config of the bundle `->scalarNode('log_path')->defaultValue('var\logs')->end()` I want to execute `php bin/console scheduler:execute` and the result: **var/logs\ not found or not writable. You should override `log_path` in your config.yml**.

Is this an OS path configuration problem? When I change `var\logs` by `var/logs` it works. Maybe this default configuration is for Windows OS specifically. 

I'm also facing another error. I have installed the bundle step by step just like the documentation says, then in route `/command-scheduler/detail/new` the form for creating a new task the fields seems to be not focusable, I can't focus any field.

Sorry for my english.

**Comment by Nightbr** [comment]
Hey, add to the log_path should be relative to app_root or kernel_root. It will be easier to manipulate and store our app logs files into the correct folder wherever you call the command.

**Comment by J-Mose** [comment]
Fixed in the v2.0 release.
The default log path is now `kernel.logs_dir`
