### ISSUE TITLE
Symfony 4 support?

### ISSUE THREAD

**Issue by fnowacki** [J-Mose/CommandSchedulerBundle#81]
Curently max version of symfony core is 3.*. Any chances for symfony 4 support?

**Comment by chrisjohnson00** [comment]
agree, however it's a breaking change for this project as it requires PHP 7.1.  Suggest it be a full point release for this project as well.

```feature #22733 Bump minimum version to PHP 7.1 for Symfony 4 (fabpot, dunglas, nicolas-grekas)```

**Comment by julienpillias** [comment]
Any update for symfony 4 ?

**Comment by chrisjohnson00** [comment]
No one has created a PR yet... feel free to create one yourself if you can.

**Comment by Soullivaneuh** [comment]
> agree, however it's a breaking change for this project as it requires PHP 7.1.

It's still not an issue. You can allow both Symfony 3 and 4.

BTW, Symfony 4.0 is strictly the same as Symfony 3.4, without the deprecated stuff.

**Comment by chrisjohnson00** [comment]
thanks @Soullivaneuh for the clarification
