### ISSUE TITLE
Compatibility with Symfony Standard Edition 3.4

### ISSUE THREAD

**Issue by mikaint** [J-Mose/CommandSchedulerBundle#87]
This bundle is not compatible with Symfony 3.4  due to restrictions in sensio/framework-extra-bundle 

SF3.4 requires sensio/framework-extra-bundle version ^5.0.0 https://github.com/symfony/symfony-standard/blob/3.4/composer.json#L22

while this bundle requires ^3.0.2"

Are there any plans to fix this issue?

**Comment by chrisjohnson00** [comment]
What issues are you seeing?  The [CI job tests](https://travis-ci.org/J-Mose/CommandSchedulerBundle/jobs/311195660) against 3.4 and hasn't identified any issue

**Comment by mikaint** [comment]
I'm using symfony/standard which requires "sensio/framework-extra-bundle": "^5.0.0",

https://github.com/symfony/symfony-standard/blob/v3.4.1/composer.json
