### ISSUE TITLE
Custom Command with dependency injection

### ISSUE THREAD

**Issue by pasqualepalmaccio** [J-Mose/CommandSchedulerBundle#92]
Hi,
i have created a custom command and it is correctly listed in command list to be executed. When i try to add a dependecy injection like 
` 
public function __construct(CustomRepository $repo)
    {

        $this->repo = $repo;

        parent::__construct();
    }
`

command disappear from list and i'm not able to schedule it. Why? Thanks, best regards

**Comment by J-Mose** [comment]
Hi,

Can you see your custom command using the `bin/console list`native command ?
Does it have the  `tags: [console.command]` in the service definition ?
